plugins {
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management'
    id 'java'
}

group = 'com.smartfleet'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

dependencies {
    implementation project(':common-lib')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}
